#!/bin/bash
set -e

# https://unix.stackexchange.com/questions/17717/refer-to-a-file-under-the-same-directory-of-a-script-found-in-path
cd "${BASH_SOURCE%/*}" || exit

# create a FIFO file, used to manage the I/O redirection from shell
PIPE=$(mktemp -u --tmpdir ${0##*/}.XXXXXXXX)
mkfifo $PIPE
export PIPE

rm -f quit.txt
# attach a file descriptor to the file
exec 3<> $PIPE

# add handler to manage process shutdown
function on_exit() {
    # this handles ctrl c
    # send command to yad through pipe
    echo "quit" >&3
    rm -f $PIPE
}
trap on_exit EXIT

function update_icon() {
    exec 3<> $PIPE         # just in case
    echo "icon:icon.png" >&3
}
export -f update_icon     

# add handler for tray icon left click
function on_click() {
    exec 3<> $PIPE         # required
    echo "clicked"
    echo "icon:icon.png" >&3
    update_icon
}
export -f on_click

# add handler for right click menu Quit entry
function on_quit() {
    echo "quit" > ./quit.txt
    exec 3<> $PIPE         # required
    echo "quit" >&3
}
export -f on_quit

# create the notification icon
yad --notification                  \
    --listen                        \
    --image="icon.png"  \
    --text="Teams Green Active"   \
    --menu="Quit!bash -c on_quit" \
    --no-middle \
    --command="bash -c on_click" <&3 &

while [ ! -f "quit.txt" ]; do
    #echo "Press [CTRL+C] to stop.."
    update_icon
    bash ./teams_green_update
    sleep 2
done
rm quit.txt
